### ISSUE TITLE
Next.js v.14.0.4

### ISSUE THREAD

**Issue by tomyedlp** [apteryxxyz/next-ws#14]
Doesn't work with Next.js v14.0.4.

```
⨯ node_modules\next-ws\client\context.js (6:54) @ eval
 ⨯ TypeError: (0 , react_1.createContext) is not a function
    at __webpack_require__ (C:\devs\NextJS\name_project\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (C:\devs\NextJS\name_project\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/layout.tsx:11:72)
    at (rsc)/./src/app/layout.tsx (C:\devs\NextJS\name_project\.next\server\app\page.js:371:1)
    at Function.__webpack_require__ (C:\devs\NextJS\name_project\.next\server\webpack-runtime.js:33:42)
```

**Comment by apteryxxyz** [comment]
I can confirm that Next WS still works on 14.0.4, can you ensure that you are have `'use client'` in the file where you're trying to use `next-ws/client` features.
